services:
  dotnet_6:
    container_name: dotnet_6
    build: .
    volumes:
      # - vendor:/var/www/html/vendor
      # - node_modules:/var/www/html/node_modules
      - ./:/home
    ports:
      - 5000:5000
# volumes:
#   vendor:
#   node_modules:
